version: '3.1'
services:
  my-mysql:
   image: mysql
   container_name: evo2-mysql
   volumes:
      - db_data:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
   ports:
     - 3307:3306

volumes:
  db_data: